// Mocks generated by Mockito 5.2.0 from annotations
// in marvel_app/test/search_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:marvel_app/core/models/comics_data_wrapper.dart' as _i2;
import 'package:marvel_app/core/repository/comics_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeComicDataWrapper_0 extends _i1.Fake implements _i2.ComicDataWrapper {
}

/// A class which mocks [ComicsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockComicsRepository extends _i1.Mock implements _i3.ComicsRepository {
  MockComicsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ComicDataWrapper> fetchComics() =>
      (super.noSuchMethod(Invocation.method(#fetchComics, []),
              returnValue:
                  Future<_i2.ComicDataWrapper>.value(_FakeComicDataWrapper_0()))
          as _i4.Future<_i2.ComicDataWrapper>);
  @override
  _i4.Future<_i2.ComicDataWrapper> searchComics(String? searchText) =>
      (super.noSuchMethod(Invocation.method(#searchComics, [searchText]),
              returnValue:
                  Future<_i2.ComicDataWrapper>.value(_FakeComicDataWrapper_0()))
          as _i4.Future<_i2.ComicDataWrapper>);
}
